#env:
#  es2020: true
#  browser: true
#  node: true
#extends:
#  - 'airbnb-base'
#  - "plugin:jest/recommended"
#plugins: ["jest"]
#parserOptions:
#  ecmaVersion: 11
#  sourceType: module
#rules:
#  no-console: 0
#  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
